/* 회원 테이블 생성 */
CREATE TABLE KITE_USER (
	USR_NO NUMBER(12) PRIMARY KEY,
	USR_ID VARCHAR2(50) UNIQUE,
	USR_PW VARCHAR2(255) NOT NULL,
	USR_NIC VARCHAR2(16) NOT NULL,
	USR_GDR VARCHAR2(1)    NOT NULL,
	USR_AGE NUMBER(3) NOT NULL,
	USR_ARA VARCHAR(12),
	USR_DT DATE NOT NULL
);

/* 회원 번호 시퀀스 생성  */
CREATE SEQUENCE SEQ_USR_NO START WITH 1;

/* 회원 관심사 (스트리머 관련) 테이블 생성 */
CREATE TABLE KITE_USR_LIKE (
	

);
